spring:
  application:
    name: ms-config-server
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Practica1Arquitectura/micro-servicio
          default-label: "main"

server:
  port: ${SERVER_PORT:8887}


